apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hello-world
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - hello-world