apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2222
  namespace: default
data:
  path: foobar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2
  namespace: default
data:
  path: foobar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-3
  namespace: default
data:
  path: foobar

