apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: feng-mc
  namespace: feng-mc
spec:
  desiredCuration: upgrade
   destroy:
     jobMonitorTimeout: 5
   install:
     jobMonitorTimeout: 5
     posthook:
       - extra_vars: {}
         name: Demo Job Template 2
         type: Job
     prehook:
       - extra_vars: {}
         name: Demo Job Template
         type: Job
     towerAuthSecret: toweraccess
   inventory: Demo Inventory
   scale:
     jobMonitorTimeout: 5
   upgrade:
     monitorTimeout: 120
     posthook:
       - extra_vars: {}
         name: Demo Job Template 2
         type: Job
     prehook:
       - extra_vars: {}
         name: Demo Job Template
         type: Job
     towerAuthSecret: toweraccess

