apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: feng-mc
  namespace: feng-mc
  resourceVersion: ""
spec:
  desiredCuration: upgrade
  install:
    towerAuthSecret: toweraccess
    prehook:
      - name: Demo Job Template
        extra_vars: {}
        type: Job
    posthook:
      - name: Demo Job Template 2
        extra_vars: {}
        type: Job
  upgrade:
    towerAuthSecret: toweraccess
    prehook:
      - name: Demo Job Template
        extra_vars: {}
        type: Job
    posthook:
      - name: Demo Job Template 2
        extra_vars: {}
        type: Job
  inventory: Demo Inventory

