apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policy-placement
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - environment
      - key: fault-domain
        operator: In
        values:
          - fault_domain
