kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: cars.feng.example.com
spec:
  group: feng.example.com
  names:
    plural: cars
    singular: car
    shortNames:
      - crs
    kind: carkind
    listKind: carkindList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
