apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git-helm
  namespace: ch-git-helm
  labels:
    name: git-sub
spec:
  pathname: 'https://github.com/open-cluster-management/multicloud-operators-subscription'
  type: Git
