apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    # apps.open-cluster-management.io/git-tag: V1.0
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-option: merge
  name: blank
spec:
  channel: acm-config-maint-groups-channel/acm-config-maint-groups-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-secondary