apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mainapp
  namespace: openshift-gitops
spec:
  destination:
    namespace: a-o-a
    name: local-cluster
  project: default
  source:
    path: helloworld
    repoURL: https://github.com/fxiang1/app-samples
    targetRevision: HEAD
syncPolicy:
  automated:
  prune: true
  selfHeal: true
  syncOptions:
  - CreateNamespace=true

