apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: feng-helloworld-applicationset
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement 
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: feng-helloworld-placement
        requeueAfterSeconds: 180
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'feng-{{name}}-helloworld'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/fxiang1/app-samples
        targetRevision: HEAD
        path: helloworld
      destination:
        server: '{{server}}'
        namespace: feng-helloworld-applicationset
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
          - ApplyOutOfSyncOnly=true
          - Validate=false
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: feng-helloworld-placement
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster

