apiVersion: v1
kind: Pod
metadata:
  name: mortgagepod-deploy
  labels:
    app: mortgagepod-mortgage
spec:
  containers:
    - name: mortgagepod-mortgage
      image: 'quay.io/fxiang1/mortgage:0.5.0'
      ports:
        - containerPort: 9080
          protocol: TCP
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
      imagePullPolicy: Always

