apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mortgagepod-subscription
  namespace: default
  labels:
    app: mortgagepod
  annotations:
    apps.open-cluster-management.io/github-path: mortgagepod
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: mortgagepod-ch/mortgagepod-channel
  placement:
    placementRef:
      name: mortgagepod-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io

