apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: app-e2e-users
      mappingMethod: claim
      name: app-e2e-htpasswd
      type: HTPasswd
    - htpasswd:
        fileData:
          name: htpasswd-d4pwb
      mappingMethod: claim
      name: feng-htpasswd
      type: HTPasswd

